CREATE DATABASE todolist;

\c todolist;

CREATE TABLE IF NOT EXISTS Tasks (
    Id UUID PRIMARY KEY NOT NULL,
    RootTaskId UUID NULL,
    Summary VARCHAR(255) NOT NULL,
    Description TEXT NOT NULL,
    CreateDate TIMESTAMPTZ DEFAULT NOW(),
    DueDate TIMESTAMPTZ,
    Priority SMALLINT NOT NULL DEFAULT 0,
    Status SMALLINT NOT NULL DEFAULT 0,
    CONSTRAINT Id_UNIQUE_T UNIQUE (Id),
    CONSTRAINT ROOT_TASK_ID_KEY FOREIGN KEY (RootTaskId) REFERENCES Tasks (Id) ON DELETE SET NULL ON UPDATE NO ACTION
);

CREATE TABLE IF NOT EXISTS Logs (
    Id UUID PRIMARY KEY NOT NULL,
    Action SMALLINT NOT NULL,
    TimestampMsec BIGINT NOT NULL,
    EntityId UUID NULL,
    EntityType VARCHAR(255) NULL,
    Payload TEXT NULL,
    CONSTRAINT Id_UNIQUE_L UNIQUE (Id)
);

CREATE INDEX SEARCH ON Tasks USING GIN (to_tsvector('english', Summary || ' ' || Description));
CREATE INDEX ROOT_TASK_ID_KEY_idx ON Tasks (RootTaskId);
CREATE INDEX SEARCH_ID ON Logs (EntityId);
CREATE INDEX SEARCH_TYPE ON Logs (EntityType);